### ISSUE TITLE
Color picker layout sometimes is broken

### ISSUE THREAD

**Issue by astelmashenko** [notwaldorf/polymer-color-picker#2]
Hi,
There is a line of code:

``` javascript
var sizeOfAColor = getComputedStyle(this.$.box.querySelector('.color')).width.replace('px', '');
```

getComputedStyle(this.$.box.querySelector('.color')).width may return 'auto', that breaks color picker. To get it return actual size requires element to be rendered.

Sorry, I do not provide jsbin example, will do when I have time.

**Comment by notwaldorf** [comment]
Hiya! I am actually working on making this an element in the PolymerElements org, and I fixed this bug over there. Stay tuned!

**Comment by DavidMRocha** [comment]
Hi, I have the same problem, as I fix it?
Thanks

**Comment by notwaldorf** [comment]
Closing! This now lives in https://github.com/polymerelements/paper-swatch-picker
