### ISSUE TITLE
rename element

### ISSUE THREAD

**Issue by Zecat** [notwaldorf/polymer-color-picker#4]
Don't this element should be called x-palette-picker to avoid name conflict with "a real color picker" ? I mean the ones providing a spectre, rgba/hsl controls, hex value... as [this one](https://github.com/David-Mulder/paper-color-picker).

**Comment by notwaldorf** [comment]
Hiya! I'm actually in the process of porting this to `PolymerElements/paper-swatch-picker`, so this will go away altogether soon :)

**Comment by notwaldorf** [comment]
Closing! This now lives in https://github.com/polymerelements/paper-swatch-picker
